<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Time\Module'                        => __DIR__ . '/Module.php',
    'Time\Controller\IndexController' => __DIR__ . '/src/Time/Controller/IndexController.php',
    'TimeTest\Framework\TestCase'        => __DIR__ . '/tests/Time/Framework/TestCase.php',
    'TimeTest\SampleTest'                => __DIR__ . '/tests/Time/SampleTest.php',
);
